
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - geodecluster.geode.apache.org
  resources:
  - locators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - geodecluster.geode.apache.org
  resources:
  - locators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - geodecluster.geode.apache.org
  resources:
  - servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - geodecluster.geode.apache.org
  resources:
  - servers/status
  verbs:
  - get
  - patch
  - update
